
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ref.
project_id = "mkgdgbihziyazbxottcw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54323
api_url = "https://api.supabase.io"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
traces = false
pubsub = false

[edge.runtime]
enabled = true

[functions]
create-demo-users = { verify_jwt = false }
